# Generated by Django 4.0.6 on 2022-08-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('areas', '0001_initial'),
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='areas.area'),
        ),
        migrations.AddField(
            model_name='animal',
            name='movement',
            field=models.ManyToManyField(related_name='animals', to='movements.movement'),
        ),
    ]
